import type {Metadata} from "next";
import {Geist, Geist_Mono, Bai_Jamjuree} from "next/font/google";
import "./globals.css";
import Head from "next/head";
import {ReactNode} from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
const baiJamjuree = Bai_Jamjuree({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'], // выбери нужные веса
    variable: '--font-bai-jamjuree',
    display: 'swap',
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <Head>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link
                href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
                rel="stylesheet"/>
        </Head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${baiJamjuree.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
